/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ISASNMPMIB_H
#define ISASNMPMIB_H

/* function declarations */
void init_IsaSNMPMIB(void);
Netsnmp_Node_Handler handle_IsaLOGIN;
Netsnmp_Node_Handler handle_IsaTIME;
Netsnmp_Node_Handler handle_IsaINT;
Netsnmp_Node_Handler handle_IsaOSINFO;

#endif /* ISASNMPMIB_H */
